version = 3.11.0
style = defaultWithAlign
runner.dialect = scala213

align.preset = most
comments.wrapSingleLineMlcAsSlc = true
docstrings.blankFirstLine = yes
docstrings.wrap = yes
docstrings.style = Asterisk
docstrings.oneline = unfold
importSelectors = singleLine
literals.float = Upper
literals.hexDigits = Upper
maxColumn = 120
newlines.afterCurlyLambda = preserve
rewrite.imports.sort = original
rewrite.rules = [
  Imports,
  SortModifiers
]
